# Generated by Django 3.2.6 on 2021-09-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_myuser_postimagemodel_postmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
