# Generated by Django 3.2.6 on 2021-09-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_delete_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='post_head_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image'),
        ),
    ]
