# Generated by Django 3.2.6 on 2021-09-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_postmodel_post_head_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarmodel',
            name='url',
            field=models.URLField(default=False),
            preserve_default=False,
        ),
    ]
