# Generated by Django 3.2.6 on 2021-09-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_navbarmodel_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=14)),
                ('text', models.TextField()),
            ],
        ),
    ]
