# Generated by Django 3.2.6 on 2021-09-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_postmodel_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
    ]
