# Generated by Django 3.2.6 on 2021-09-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_alter_postmodel_post_head_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_title',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
