# Generated by Django 3.2.6 on 2021-09-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_alter_postmodel_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_title',
            field=models.CharField(max_length=5),
        ),
    ]
